# importing of .env file
spring.config.import=optional:file:.env[.properties]

# Application Configuration
server.port=${SERVER_PORT}

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=${LIQUIBASE_CHANGELOG}

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}